//cac thong bao
module.exports = {
  ERROR_MESSAGE: {
    ROOM_TICKET: {
      EXIST: "ROOM_TICKET_EXIST",
      NOT_FOUND: "ROOM_TICKET_NOT_EXIST",
      FAIL_DELETE:"ROOM_DELETE_FAIL",
      FAIL_UPDATE:"ROOM_UPDATE_FAIL",
      CREATE_FAIL:"CREATE_ROOM_FAIL"
    }
  },
  SUCCESS_MESSAGE: {
    ROOM_TICKET: {
      PASS_CREATE:"ROOM_TICKET_CREATE_SUCCESS"
    }
  }
};
